CREATE TABLE Employee(
	ID INT PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	GENDER VARCHAR(255) NOT NULL,
	AGE INT NOT NULL,
	DESIGNATION VARCHAR(255) NOT NULL,
	SALARY INT NOT NULL
);

--DROP TABLE Employee;
SELECT * FROM Employee;
GO